# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "doctopdf"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["gauravgaur111"]
  s.date = "2012-05-05"
  s.description = "Jruby gem to convert microsoft office documents to pdf. Useful to render office documents in browser in rails web app settings."
  s.email = "gauravgaur111@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "doctopdf.gemspec",
    "jar/conf/document-formats.js",
    "jar/jod/commons-cli-1.1.jar",
    "jar/jod/commons-io-1.4.jar",
    "jar/jod/jodconverter-core-3.0-beta-4.jar",
    "jar/jod/json-20090211.jar",
    "jar/jod/juh-3.2.1.jar",
    "jar/jod/jurt-3.2.1.jar",
    "jar/jod/ridl-3.2.1.jar",
    "jar/jod/unoil-3.2.1.jar",
    "lib/doctopdf.rb",
    "test/helper.rb",
    "test/test_doctopdf.rb"
  ]
  s.homepage = "http://github.com/gauravgaur111/doctopdf"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.15"
  s.summary = "Jruby gem to convert microsoft office documents to pdf using openoffice and jodconverter libraries"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.1.3"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.3"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.1.3"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
      s.add_dependency(%q<simplecov>, [">= 0"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.1.3"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
    s.add_dependency(%q<simplecov>, [">= 0"])
  end
end

